version: "3"

#services:
#  postgres:
#    container_name: postgres
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: mypassword
#    ports:
#      - "5432:5432"
#    volumes:
#      - dbdata:/var/lib/postgresql/data
#
#  app:
#    container_name: app
#    build:
#      context: .
#    depends_on:
#      - "postgres"
#
#volumes:
#  dbdata: # create the volume for persisting data.
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata: # create the volume for persisting data.